### ISSUE TITLE
Crear Drive compartido para administrar documentos del grupo. 

### ISSUE THREAD

**Issue by MLVELEZO** [SantiagoQuevedo/EstacionesMeteorologicas_Equipo9#5]
Enlace del Drive: https://drive.google.com/drive/folders/1n6WaxC53okZCSFMAsq9fHUPWfK-ElikL?usp=sharing

**Comment by SantiagoQuevedo** [comment]
Enlace del Drive: https://drive.google.com/drive/folders/1n6WaxC53okZCSFMAsq9fHUPWfK-ElikL?usp=sharing
